// Auto-generated from DiseasesListClient.tsx — slug → Devanagari name
// Used in generateMetadata for Hindi search intent (titles/descriptions)
export const HINDI_NAMES: Record<string, string> = {
  'psoriasis': 'चम्बल (सोरायसिस)',
  'scalp-psoriasis': 'सर की चम्बल / बालों वाली चम्बल',
  'guttate-psoriasis': 'बिंदु चम्बल / छोटे दाने वाली चम्बल',
  'atopic-dermatitis': 'खुजली-सूजन रोग / एटॉपिक एक्जिमा',
  'eczema': 'एक्जिमा',
  'vitiligo': 'सफेद दाग',
  'acne': 'मुहांसे',
  'urticaria': 'पित्ती',
  'lichen': 'लाइकेन',
  'acanthosis-nigricans': 'काली गठीली त्वचा',
  'ringworm': 'दाद / दाद-खाज / Tinea',
  'wart': 'मस्सा / मसा / गड्ढा मसा',
  'molluscum-contagiosum': 'चेचक जैसी फुंसियां / वायरल दाने',
  'chickenpox': 'चेचक / माता / छोटी माता',
  'nail-fungus': 'नाखून का फंगस',
  'melasma': 'झाइयां / चेहरे का दाग',
  'post-covid-syndrome': 'पोस्ट-कोरोना थकान / Long COVID',
  'breast-fibroadenoma': 'छाती की गांठ / स्तन गांठ',
  'postpartum-depression': 'प्रसव के बाद का अवसाद',
  'allergic-rhinitis': 'नाक की एलर्जी / प्रतिरोधी नज़ला',
  'recurrent-ear-infection': 'बार बार कान का दर्द / कान पकना',
  'tinnitus': 'कान में सीटी / भनभनाहट',
  'chronic-otitis-media': 'कान का पुराना दर्द / कान बाहर',
  'vocal-cord-nodule': 'आवाज़ की गांठ / गले की गांठ',
  'delayed-milestones': 'विकास में देरी / बच्चे का धीरे बढ़ना',
  'sciatica': 'सायटिका',
  'disc-bulge': 'डिस्क खिसकना',
  'back-pain': 'कमर दर्द',
  'arthritis': 'गठिया / वात रोग',
  'psoriatic-arthritis': 'चम्बल वाला गठिया',
  'rheumatoid-arthritis': 'रूमेटाइड आर्थराइटिस',
  'gout': 'गाउट',
  'cervical-spondylosis': 'सर्वाइकल / गर्दन दर्द',
  'ankylosing-spondylitis': 'रीढ़ की सूजन',
  'frozen-shoulder': 'जमा हुआ कंधा',
  'plantar-fasciitis': 'एड़ी का दर्द',
  'tennis-elbow': 'कोहनी का दर्द',
  'osteoarthritis': 'घुटने का दर्द / जोड़ों की घिसाव',
  'juvenile-arthritis': 'बच्चों का गठिया',
  'acidity': 'तेज़ाब / सीने की जलन',
  'ibs': 'आईबीएस',
  'piles': 'बवासीर',
  'fissure': 'फिशर',
  'anal-fistula': 'भगंदर / नली रोग',
  'constipation': 'कब्ज / क़ब्ज़',
  'ulcerative-colitis': 'अल्सरेटिव कोलाइटिस',
  'fatty-liver': 'जिगर में चर्बी',
  'mouth-ulcer': 'मुँह के छाले',
  'gastritis': 'पेट की सूजन / गैस्ट्राइटिस',
  'gallstones': 'पित्ताशय की पथरी',
  'gerd': 'अम्लपित्त / सीने की जलन',
  'dyspepsia': 'बदहज़मी / अपच / अजीर्ण',
  'worm-infestation': 'Worms in Children',
  'lactose-intolerance': 'दूध न पचना / डेयरी से परेशानी',
  'migraine': 'माइग्रेन',
  'anxiety': 'चिंता',
  'depression': 'अवसाद',
  'insomnia': 'अनिद्रा',
  'obsessive-compulsive-disorder': 'ओसीडी',
  'chronic-fatigue-syndrome': 'Chronic Thakan Rog / हमेशा थकान',
  'ptsd': 'मानसिक आघात विकार / Post-Traumatic',
  'pcod': 'पीसीओडी',
  'leucorrhoea': 'श्वेत प्रदर',
  'endometriosis': 'एंडोमेट्रियोसिस',
  'uterine-fibroid': 'बच्चेदानी की गांठ / रसौली',
  'menopause': 'रजोवृत्ति / महावारी बंद',
  'ovarian-cyst': 'अंडाशय की गांठ / सिस्ट',
  'dysmenorrhoea': 'माहवारी का दर्द',
  'hairfall': 'बाल झड़ना',
  'alopecia': 'गंजापन',
  'dandruff': 'रूसी',
  'asthma': 'दमा',
  'allergy': 'एलर्जी',
  'sinusitis': 'साइनसाइटिस',
  'nasal-polyp': 'नाक की रसौली / गांठ',
  'recurrent-cold': 'बार बार सर्दी-जुकाम / Weak Immunity',
  'bronchitis': 'श्वास नली की सूजन / खांसी की बीमारी',
  'thyroid': 'थायरॉइड की कमी',
  'hyperthyroidism': 'थायरॉइड का बढ़ना',
  'hashimoto-thyroiditis': 'हाशिमोटो थायरॉइड',
  'prediabetes': 'प्रीशुगर / इंसुलिन रेज़िस्टेंस',
  'sjogrens-syndrome': 'स्जोग्रेन सिंड्रोम',
  'adhd': 'धयान की कमी / Hyperactivity',
  'autism': 'ऑटिज्म',
  'adenoids': 'नाक की गांठ',
  'tonsillitis': 'टॉन्सिल की सूजन',
  'bedwetting': 'बिस्तर गीला करना',
  'teething-trouble': 'दाँत निकलने की तकलीफ',
  'stye': 'गुहेरी / आँखों की फुंसी',
  'dry-eye-syndrome': 'आँखों की जलन / सूखी आँखें',
  'varicose-veins': 'नसों की सूजन',
  'male-infertility': 'पुरुष निःशक्तता / बीज दोष',
  'erectile-dysfunction': 'नपुंसकता / मर्दों की कमज़ोरी',
  'kidney-stone': 'गुर्दे की पथरी',
  'recurrent-uti': 'बार बार मूत्र संक्रमण',
  'bph': 'प्रोस्टेट का बढ़ना',
  'bells-palsy': 'चेहरे का लकवा',
  'carpal-tunnel-syndrome': 'हाथ सुन्नपन / CTS',
  'trigeminal-neuralgia': 'चेहरे में बिजली का दर्द',
  'vertigo': 'चक्कर आना / सर घूमना',
}

// Short form for <title> — pehla naam, slash ke pehle wala
export function hindiShort(slug: string): string | null {
  const h = HINDI_NAMES[slug]
  if (!h) return null
  return h.split('/')[0].trim()
}
